### PR TITLE
Add a function to return index

### PR DESCRIPTION
**Pull request by yktakaha4**
Thanks for the great library!

I thought it would be more flexible to add a function that returns the index of the array (e.g., to use the value of the object corresponding to index)

I have already created a test and confirmed that it does not break the existing behavior.

### CODE REVIEW

**Comment by BeLi4L** [comment]
I personally feel like this kind of utility methods doesn't really belong in such a library, which is focused on the distance itself, not a specific use-case related to that distance.

I'm not sure why `closest` was added in the first place :shrug:

**Comment by ka-weihe** [comment]
> I thought it would be more flexible to add a function that returns the index of the array (e.g., to use the value of the object corresponding to index)

@yktakaha4 I agree, that is probably how `closest` should have been, but I don't think I will add your changes now (but thank you, I will maybe open this again later). I have to think about it. For now, you just have to do it in your own code.

> I'm not sure why closest was added in the first place

@BeLi4L `closest` was added because it is possible to do some very powerful optimizations when you compute the distance between one string and an array of multiple strings. I have not added these optimizations yet, but that is why `closest` is in the source. `closest` is also how this package is mostly used by people.

**Comment by BeLi4L** [comment]
> @BeLi4L `closest` was added because it is possible to do some very powerful optimizations when you compute the distance between one string and an array of multiple strings

Good point! I didn't think of that :+1: 

Just curious, since I only use `distance`, do you have examples of use cases of `closest`? :thinking:

**Comment by ka-weihe** [comment]
> Just curious, since I only use distance, do you have examples of use cases of closest?

Imagine you have an array of all english words and a misspelled word.

Then you would simply do ...
```
closest(misspelled_word, all_english_words)
```

... to find the correct word.

**Pull request closed without merging**
